In [1]:
# Global setting:
import pybamm as pb;import pandas as pd   ;import numpy as np;import os;import matplotlib.pyplot as plt
from scipy.io import savemat,loadmat;from pybamm import constants,exp;
import matplotlib as mpl; fs=17; 
font = {'family' : 'Times New Roman',
        #'weight' : 'bold',
        'size'   : fs}
mpl.rc('font', **font)

In [8]:
BasicPath = 'D:/OneDrive - Imperial College London/SimDataSave/P3R10/IC_HPC/a_1_sol_Dec=1e_20_scan_ddsd_elely_2/'; 
Dict_2sol_scan2 = loadmat( BasicPath+'2th Scan/'+'2th Scan-for_AGE_only.mat')
Dict_2sol_scan2["CDend EC concentration [mol.m-3]"][-1,:]

array([-687.14817026, -687.12176703, -687.06853592, -686.98708854,
       -686.87339817, -686.71498761, -686.46640889, -685.95982802,
       -684.59693576, -684.99862977, -693.16448976, -636.30861204,
       -529.28958342, -381.41285793, -198.45082376,   15.72726125,
        258.38711701,  527.52171385,  821.61444878, 1139.49493944,
       1313.62848519, 1320.49529326, 1327.36147081, 1334.22702035,
       1341.09194437, 1347.95624535, 1354.81992579, 1361.68298817,
       1368.54543495, 1375.4072686 , 1382.2684916 , 1389.1291064 ,
       1395.98911544, 1402.84852119, 1409.70732606, 1416.5655325 ,
       1423.42314294, 1430.28015978, 1437.13658546, 1443.99242236,
       1483.29236443, 1551.41203777, 1615.89482842, 1676.75246869,
       1733.99490946, 1787.6306303 , 1837.66689452, 1884.10995642,
       1926.96522673, 1966.23740083, 2001.93055341, 2034.04820242,
       2062.59334409, 2087.56846019, 2108.97549815, 2126.81582387,
       2141.09014671, 2151.79841576, 2158.9396859 , 2162.51195

In [9]:
BasicPath = 'D:/OneDrive - Imperial College London/SimDataSave/P3R10/IC_HPC/a_1_sol_Dec=1e_20_scan_ddsd_elely_2/'; 
Dict_2sol_scan1 = loadmat( BasicPath+'1th Scan/'+'1th Scan-for_AGE_only.mat')
Dict_2sol_scan1["CDend EC concentration [mol.m-3]"][-1,:]

array([-3028.36502601, -2975.00514957, -2880.93747119, -2758.38114673,
       -2614.17543102, -2451.76612717, -2273.04016681, -2079.16259525,
       -1870.92383234, -1648.90188326, -1413.54427676, -1165.21262239,
        -904.20866569,  -630.79057161,  -345.18375989,   -47.58862978,
         261.8134233 ,   582.85472882,   915.37589729,  1259.21896733,
        1440.36599836,  1447.15415611,  1453.94209218,  1460.7298098 ,
        1467.5173122 ,  1474.30460256,  1481.09168404,  1487.87855974,
        1494.66523276,  1501.45170615,  1508.23798292,  1515.02406606,
        1521.80995854,  1528.59566326,  1535.38118312,  1542.16652098,
        1548.95167966,  1555.73666197,  1562.52147065,  1569.30610845,
        1608.20388981,  1675.62349752,  1739.44381497,  1799.67444491,
        1856.32424464,  1909.40134095,  1958.91314229,  2004.86634927,
        2047.26696414,  2086.12030012,  2121.4309912 ,  2153.20300289,
        2181.43964458,  2206.1435838 ,  2227.31686281,  2244.96091787,
      

In [10]:
BasicPath = 'D:/OneDrive - Imperial College London/SimDataSave/P3R10/IC_HPC/a_1_sol_Dec=1e_20_scan_ddsd_elely_2/'; 
Dict_2sol_scan3 = loadmat( BasicPath+'3th Scan/'+'3th Scan-for_AGE_only.mat')
Dict_2sol_scan3["CDend EC concentration [mol.m-3]"][-1,:]

array([ 750.6050993 ,  750.34966035,  749.84142364,  749.08615317,
        748.09376795,  746.88020737,  745.47064431,  743.90504322,
        742.2480692 ,  740.60771861,  739.17393308,  738.31897228,
        738.99739576,  745.28751692,  761.01822196,  798.01919975,
        885.10295533, 1041.74003187, 1253.19391847, 1502.46723358,
       1646.58730499, 1653.3379392 , 1660.08926273, 1666.84127554,
       1673.59397761, 1680.34736891, 1687.10144944, 1693.8562192 ,
       1700.6116782 , 1707.36782648, 1714.12466404, 1720.88219095,
       1727.64040723, 1734.39931297, 1741.15890821, 1747.91919305,
       1754.68016756, 1761.44183186, 1768.20418604, 1774.96723022,
       1813.74172107, 1881.13029107, 1945.07285984, 2005.54195148,
       2062.50899164, 2115.9469668 , 2165.83209328, 2212.1447952 ,
       2254.87019904, 2293.99829751, 2329.52388983, 2361.44636724,
       2389.76938494, 2414.50044313, 2435.65038988, 2453.23285369,
       2467.26361273, 2477.75991001, 2484.73972697, 2488.22103