In [1]:
# magic lines that avoid re-start 
%load_ext autoreload
%autoreload 2
import pybamm as pb;import pandas as pd   ;import numpy as np;
import os;
import matplotlib.pyplot as plt;import os;import imageio
from scipy.io import savemat,loadmat;from pybamm import constants,exp;import matplotlib as mpl; fs=17; # or we can set import matplotlib.pyplot as plt then say 'mpl.rc...'
import openpyxl
import traceback
import multiprocessing
import scipy.optimize
import timeit
import random;import time, signal
fs=17; # python -m ipykernel install --user --name=EnvPBGEM_Linux --display-name "Python_Linux"
font = {'family' : 'DejaVu Sans','size'   : fs}
mpl.rc('font', **font)

In [6]:
# Reload all scans in this round! 
# BasicPath = 'D:/OneDrive - Imperial College London/SimDataSave/P2_R8_FromSimon/'; 
BasicPath = os.path.expanduser("~/EnvPBGEM_Linux/SimSave/P2_R9_Dim/") # for Linux

Targets = ["Exp_3_HPC"]
Scan_Num = [3,]
Test_MultiTask_Long = {}
for target,scan_num in zip(Targets,Scan_Num):
    Test_MultiTask_Long[target] = {}
    Scans = np.arange(1,scan_num+1,1).tolist()
    for scan in Scans:
        Test_MultiTask_Long[target][str(scan)]={}
        try:
            Test_MultiTask_Long[target][str(scan)] = loadmat( 
            BasicPath  +   target+ "/" # +  str(scan) + "/" 
            + str(scan)+ "-StructDara_for_Mat.mat")
        except:
            print(f"Nothing in {target}, Scan {scan}")

In [17]:
# Reload all scans in this round! 
# BasicPath = 'D:/OneDrive - Imperial College London/SimDataSave/P2_R8_FromSimon/'; 
BasicPath = os.path.expanduser("~/EnvPBGEM_Linux/SimSave/P2_R9_Dim/") # for Linux

Targets = ["Exp_3_off"]
Scan_Num = [3,]
Exp_3_off = {}
for target,scan_num in zip(Targets,Scan_Num):
    Exp_3_off[target] = {}
    Scans = np.arange(1,scan_num+1,1).tolist()
    for scan in Scans:
        Exp_3_off[target][str(scan)]={}
        try:
            Exp_3_off[target][str(scan)] = loadmat( 
            BasicPath  +   target+ "/" # +  str(scan) + "/" 
            + str(scan)+ "-StructDara_for_Mat.mat")
        except:
            print(f"Nothing in {target}, Scan {scan}")

Nothing in Exp_3_off, Scan 3


In [19]:
print(Exp_3_off["Exp_3_off"]["1"]["CD Terminal voltage [V]"])

[[array([[4.17440177, 4.08721902, 4.06339   , 4.03417723, 3.98142341,
          3.92894835, 3.88122315, 3.83324036, 3.78868878, 3.73769788,
          3.68875236, 3.64877635, 3.61117359, 3.56728698, 3.51302846,
          3.45985397, 3.41007834, 3.31300779, 3.16426501, 2.87174533,
          2.50001   ]])
  array([[4.17259121, 4.08550669, 4.06150837, 4.03136212, 3.97771046,
          3.9246036 , 3.87555876, 3.82911938, 3.78436888, 3.73244575,
          3.68374147, 3.64369463, 3.60462176, 3.55727918, 3.50213317,
          3.44555631, 3.39730172, 3.26960815, 3.10823236, 2.64303639,
          2.50001   ]])
  array([[4.17247765, 4.08384861, 4.05974511, 4.02683553, 3.97132163,
          3.91743607, 3.86774116, 3.82162332, 3.77506861, 3.7213288 ,
          3.67329681, 3.63280706, 3.59041421, 3.53705508, 3.48224469,
          3.42785199, 3.34880082, 3.19589598, 2.93393244, 2.56674393,
          2.50001   ]])
  array([[4.1722421 , 4.08089232, 4.05646224, 4.01882396, 3.96109432,
          3.905212

In [20]:
print(Test_MultiTask_Long["Exp_3_HPC"]["1"]["CD Terminal voltage [V]"])

KeyError: 'CD Terminal voltage [V]'

In [12]:
print(Test_MultiTask_Long["Test_MultiTask_Long"]["1"]['CDend Throughput capacity [kA.h]'] ) # 
print(Test_MultiTask_Long["Test_MultiTask_Long"]["1"]['CDend Throughput capacity [A.h]'] ) # 
print(Test_MultiTask_Long["Test_MultiTask_Long"]["1"]['Cyc_Update_Index'] ) # 

[[0.00489179 0.0048789  0.00487447 0.00487081 0.00486761 0.00486472
  0.00486205 0.00485957 0.00485723 0.00485501 0.0048529 ]]
[[4.89178657 4.8788953  4.87446538 4.87081346 4.86761209 4.86471874
  4.86205434 4.85956971 4.85723133 4.85501492 4.85290299]]
[[  0  50  50 100 100 150 150 200 200 250 250 300 300 350 350 400 400 450
  450 500 500]]


In [15]:
print(len(Test_MultiTask_Long["Test_MultiTask_Long"]["1"]['CDend Throughput capacity [kA.h]'][0]) ) # 
print(len(Test_MultiTask_Long["Test_MultiTask_Long"]["1"]['CDend Throughput capacity [A.h]'][0]) ) # 
print(len(Test_MultiTask_Long["Test_MultiTask_Long"]["1"]['Cyc_Update_Index'][0]) ) # 

11
11
21
